language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
before_install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
install:
    - python setup.py install
script:
    - nosetests
